logo: /assets/images/norwerty.svg
theme: jekyll-theme-minimal
title: The Norwerty Keyboard Layout
description: A Norwegian keyboard layout for US keyboards
show_downloads: false
google_analytics: UA-37898375-13
